version: '2'
services:
  carx-test:
    build: .
    command: spring-boot:run
    ports:
      - "4567:4567"
    depends_on:
      - mongodb
      - mysql
  mongodb:
      image: mongo:latest
  mysql:
      image: mysql:latest
      environment:
          - MYSQL_ROOT_PASSWORD=123456
