version: '2'
services:
  carx-test:
    build: .
    command: spring-boot:run
    ports:
      - "4567:4567"
    links:
      - mongodb
      - mysql
  mongodb:
      image: mongo:latest
      ports:
        - "27017:27017"
  mysql:
      image: mysql:latest
      ports:
        - "3316:3306"
      environment:
          - MYSQL_ROOT_PASSWORD=123456
          - MYSQL_DATABASE=carx
