CREATE SCHEMA `carx` DEFAULT CHARACTER SET utf8 ;

create table customer (
      id integer generated by default as identity,
      uuid varchar(255),
      primary key (id)
);

create table activity (
      id integer generated by default as identity,
      created timestamp,
      customer_id integer,
      value integer,
      primary key (id)
);
